name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build --build-arg PGID=$(id -g) --build-arg PUID=$(id -u) -t Auto-add-network-to-docker-container -f prod.Dockerfile /

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag Auto-add-network-to-docker-container pytonballoon810/Auto-add-network-to-docker-container:latest
        docker push pytonballoon810/Auto-add-network-to-docker-container:latest
